version: 1
AppDir:
  path: AppDir
  app_info:
    id: polycrys-gen
    name: PolyCrysGen
    icon: PolyCrysGen
    version: latest
    exec: usr/bin/PolyCrysGen.sh
    exec_args: $@
  apt:
    arch: amd64
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse'
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse'
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse'
    include:
      - python3
      - python3-pip
      - python3-venv
      - libstdc++6
    exclude:
      - perl
      - perl-base
  files:
    include:
      - usr/lib/atomsk
      - usr/lib/python-venv
      - usr/bin/PolyCrysGen.sh
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*
AppImage:
  arch: x86_64
  update-information: !ENV ${UPDATE_INFO}
  sign-key: None
