name: Build and Release AppImage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download appimagetool
      run: |
        mkdir -p tools
        cd tools
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ls -l
        cd ..

    - name: Add appimagetool to PATH
      run: |
        echo "$PWD/tools" >> $GITHUB_PATH
        echo "$GITHUB_PATH"  # Print the updated PATH variable for debugging purposes

    - name: Create directories usr/bin and usr/lib
      run: |
        mkdir -p PolyCrysGen/AppDir/usr/bin
        mkdir -p PolyCrysGen/AppDir/usr/lib

    - name: Download and unpack atomsk binary
      run: |
        wget -q https://atomsk.univ-lille.fr/code/atomsk_b0.13.1_Linux-amd64.tar.gz
        tar -xzf atomsk_b0.13.1_Linux-amd64.tar.gz
        mv ./atomsk_b0.13.1_Linux-amd64/atomsk PolyCrysGen/AppDir/usr/lib/

    - name: Copy PolyCrysGen.sh script
      run: cp PolyCrysGen.sh PolyCrysGen/AppDir/usr/bin/

    - name: Set up Python and ASE
      run: |
        python3 -m venv PolyCrysGen/AppDir/usr/lib/python-venv
        source PolyCrysGen/AppDir/usr/lib/python-venv/bin/activate
        pip install --upgrade pip
        pip install --upgrade git+https://gitlab.com/ase/ase.git@master
        deactivate

    - name: Build AppImage
      run: |
        ./tools/appimagetool-x86_64.AppImage PolyCrysGen/AppDir -n PolyCrysGen.AppImage

    - name: Upload AppImage as release artifact
      uses: actions/upload-artifact@v2
      with:
        name: PolyCrysGen.AppImage
        path: PolyCrysGen.AppImage
